# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FSCalender' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'FSCalendar'

  # Pods for FSCalender

  target 'FSCalenderTests' do

  end

  target 'FSCalenderUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
